### ISSUE TITLE
Add instructions to home page

### ISSUE THREAD

**Issue by reinhold-willcox** [avivajpeyi/ludum_dare_49#22]
Exactly what the title says.

Need to explain the game controls, as well as the color matching requirement.

Might also want to add some backstory (intergalactic warfare!!) though that could be overkill...

**Comment by avivajpeyi** [comment]
I worked on this during a cheeky lunch break :D 

making PR now

**Comment by avivajpeyi** [comment]
lol, woops i didnt add info about the color matching requirements! 

- [ ] Color matching 
- [ ] Backstory?
